#!/usr/bin/env bash

set -euo pipefail

# shellcheck disable=SC2329
on_interrupt() {
    trap - INT TERM
    echo "Script interrupted." >&2
    exit 130
}
trap on_interrupt INT TERM

echo "Adding Fastfetch to '~/.bashrc'..."

failed() {
    echo "Failed to add Fastfetch to '~/.bashrc'." >&2
    exit 1
}

echo "fastfetch" >> "$HOME"/.bashrc || failed

echo "Successfully added Fastfetch to '~/.bashrc'."
exit 0