#!/usr/bin/env bash

set -euo pipefail

# shellcheck disable=SC2329
on_interrupt() {
    trap - INT TERM
    echo "Script interrupted." >&2
    exit 130
}
trap on_interrupt INT TERM

if [ "$EUID" -ne 0 ]; then
    SCRIPT_HOME="$HOME"
else
    SCRIPT_HOME="$SUDO_HOME"
fi

ACTUAL_SCRIPT_NAME=$(basename "$0")
CLEANED_SCRIPT_NAME="${ACTUAL_SCRIPT_NAME#[0-9]*-}"
SCRIPT_STATE="/var/lib/dank-bluebuild/post-login-setup/script.d/$CLEANED_SCRIPT_NAME.completed"
SCRIPT_HOME_STATE="$SCRIPT_HOME/.local/state/dank-bluebuild/post-login-setup/script.d/$CLEANED_SCRIPT_NAME.completed"

if [ -f "$SCRIPT_STATE" ] || [ -f "$SCRIPT_HOME_STATE" ]; then
    echo "Script '$CLEANED_SCRIPT_NAME' already completed."
    exit 0
fi

echo "Adding Fastfetch to '~/.bashrc'..."
if ! echo "fastfetch" >> "$SCRIPT_HOME"/.bashrc; then
    echo "Failed to add Fastfetch to '~/.bashrc'." >&2
    exit 1
fi
echo "Successfully added Fastfetch to '~/.bashrc'."

mkdir -p "$(dirname "$SCRIPT_HOME_STATE")"
touch "$SCRIPT_HOME_STATE"
exit 0
