#!/usr/bin/env bash

set -euo pipefail

# shellcheck disable=SC2329
on_interrupt() {
    trap - INT TERM
    echo "Script interrupted." >&2
    exit 130
}
trap on_interrupt INT TERM

echo "Initializing Starship..."

failed() {
    echo "Failed to initialize Starship in '~/.bashrc'." >&2
    exit 1
}

echo "eval \"\$(starship init bash)\"" >> "$HOME"/.bashrc || failed

echo "Successfully initialized Starship in '~/.bashrc'."
exit 0