#!/usr/bin/env bash

set -euo pipefail

# shellcheck disable=SC2329
on_interrupt() {
    trap - INT TERM
    echo "Script interrupted." >&2
    exit 130
}
trap on_interrupt INT TERM

failed() {
    echo "Failed to restore ${USER}'s backup." >&2
    exit 1
}

echo "Attempting to restore ${USER}'s backup..."

if [ "$EUID" -ne 0 ]; then
    echo "Please run this script as root." >&2
    exit 1
fi

TEMP_MOUNTPOINT=$(mktemp -d)
mount -o subvolid=5 -L WD-1TB "$TEMP_MOUNTPOINT"

echo "Temporarily mounted WD-1TB at '$TEMP_MOUNTPOINT'."

# shellcheck disable=SC2329
cleanup() {
    umount "$TEMP_MOUNTPOINT" 2>/dev/null || true
    rmdir "$TEMP_MOUNTPOINT" 2>/dev/null || true
}
trap cleanup EXIT

if btrfs subvolume list "$TEMP_MOUNTPOINT"  | awk '{print $NF}' | grep -qx "@samsung_backup"; then
    echo "Confirmed that Btrfs subvolume '@samsung_backup' exists in WD-1TB."
else
    echo "Btrfs subvolume '@samsung_backup' does not exist in WD-1TB."
    echo "Nothing to restore."
    failed
fi

if mountpoint -q "$HOME/.mount/SAMSUNG@STORAGE"; then
    echo "Confirmed that '~/.mount/SAMSUNG@STORAGE' is a successful mountpoint."
else
    echo "Nothing was mounted at '~/.mount/SAMSUNG@STORAGE'."
    echo "Nowhere to restore to."
    failed
fi

echo "Rsync starting..."

if rsync -ah --info=progress2 "$TEMP_MOUNTPOINT"/@samsung_backup/ "$HOME"/.mount/SAMSUNG@STORAGE/; then
    echo "Successfully restored data from '@samsung_backup' to '~/.mount/SAMSUNG@STORAGE'."
else
    echo "Failed to restore data from '@samsung_backup' to '~/.mount/SAMSUNG@STORAGE'." >&2
    failed
fi

echo "Sucessfully restored ${USER}'s backup."
exit 0